language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install beautifulsoup4
    #For Coverage Report
# command to run tests
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - python WebScraperForTAGv1.py
  - coverage run WebScraperForTAGv1-test.py
branches:
  only:
   - master
after_success:
    - coveralls
    - codecov
